#!/usr/local/bin/python3.7
from callhome import app


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, ssl_context=('/etc/dehydrated/certs/uxx-001.pc-mania.nl/cert.pem',
                                                    '/etc/dehydrated/certs/uxx-001.pc-mania.nl/privkey.pem'))

